title: h0we
author:
  name: camh0we
  email: cam@camh0we.com
repository: camh0we/h0weblog
description: >
  h0we did you do that
tag_permalink_style: pretty
show_excerpts: true # set to true to show excerpts on the homepage

tag_page_layout: tag_page
tag_page_dir: tag

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"
  skin: dark

  # generate social links in footer
  social_links:
    github: camh0we

# Build settings
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-tagging

url: https://camh0we.com
baseurl: ""
